# Generated by Django 5.0.3 on 2024-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_orderpayment_deduction_alter_altercart_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcart',
            name='owner_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
