# Generated by Django 5.0.3 on 2025-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sellcart_owner_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sellcart',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
