# Generated by Django 5.0.3 on 2024-12-08 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_clientdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='cover_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='commission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='header',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='new_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='old_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='perform_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perform_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Phone number with minimum 8 numbers.', regex='^\\+?1?\\d{7,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='post_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
