# Generated by Django 5.0.3 on 2024-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_followus_title'),
        ('users', '0017_clientdetails_cover_video_url_vendor_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='post_code',
        ),
        migrations.AddField(
            model_name='vendor',
            name='post_code',
            field=models.ManyToManyField(blank=True, to='core.validarea'),
        ),
    ]
