# Generated by Django 5.0.3 on 2025-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_vendor_post_code_vendor_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_charge',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission',
            field=models.PositiveIntegerField(default=0, verbose_name='Owner commission percentage'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='owner_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Owner commission'),
        ),
    ]
