# Generated by Django 5.0.3 on 2024-12-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0017_weeklyvariant_product_weekly_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyvariant',
            options={'ordering': ['id']},
        ),
    ]
